import * as esbuild from 'esbuild';
import process from "process";
import builtins from "builtin-modules";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const isProduction = process.argv.includes('production');

const config = {
    banner: {
        js: banner,
    },
    entryPoints: ['src/main.js'],
    bundle: true,
    external: [
        "obsidian",
        "electron",
        "@codemirror/autocomplete",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/view",
        "@lezer/common",
        "@lezer/highlight",
        "@lezer/lr",
        ...builtins],
    format: "cjs",
    platform: 'node',
    target: 'node18',
    logLevel: "info",
    sourcemap: !isProduction,
    treeShaking: true,
    outfile: "main.js",
    minify: isProduction,
};

try {
    await esbuild.build(config);
    console.log('Build completed successfully');
} catch (error) {
    console.error('Build failed:', error);
    process.exit(1);
} 