[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# Markers
markers =
    unit: Unit tests
    integration: Integration tests
    e2e: End-to-end tests
    slow: Slow running tests
    api: API tests
    db: Database tests

# Test configuration
addopts = 
    --verbose
    --cov=src
    --cov-report=term-missing
    --cov-report=html
    --cov-report=xml
    --no-cov-on-fail
    --tb=short

# Environment variables for testing
env =
    ENVIRONMENT=test
    VAULT_PATH=tests/data/test_vault
    AUDIO_FILES_DIR=tests/data/test_audio
    RAW_EMAILS_DIR=tests/data/test_emails/raw
    PROCESSED_EMAILS_DIR=tests/data/test_emails/processed
    RAG_VECTOR_DB_PATH=tests/data/test_vector_db

# Logging configuration
log_cli = True
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)
log_cli_date_format = %Y-%m-%d %H:%M:%S 